[package]
name = "opus"
version = "1.2.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[lib]

[dependencies]
starknet = ">= 2.8.0"
wadray = ">= 0.5.0"
ekubo = { git = "https://github.com/EkuboProtocol/abis", commit = "edb6de8c9baf515f1053bbab3d86825d54a63bc3" }

[[target.starknet-contract]]
sierra = true
